version: "3.5"

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    env_file: .env
    command: mysqld --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1' $$MYSQL_DATABASE"
      interval: 3s
      timeout: 1s
      retries: 5

  server:
    image: portfolio-server
    restart: always
    build:
      context: ./backend
    ports:
      - "3001:3001"
    env_file: .env
    depends_on:
      - db
      
  client:
    image: portfolio-client
    build:
      context: ./frontend-react
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mysql: