version: '3.5'

services:
  db:
    container_name: db
    image: mysql:5.7
    expose: 3306
    ports:
      - "3306:3306"
  server:
    container_name: server
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PROFILE_USER=root
      - PROFILE_PASSWORD=root
      - PROFILE_HOST=localhost
      - PROFILE_PORT=3306
      - PROFILE_DATABASE=user
    depends_on:
      - db
  client:
    container_name: client
    build: ./frontend-react
    env_file: .env
    ports:
      - "3000:3000"
    volumes: 
      - ./frontend-react:/usr/src/app
    depends_on: 
      - server
